import "./globals.css";
import { GeistSans } from "geist/font/sans";
import Categories from "../components/Categories";
import Navbar from "../components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Navbar />
        <div className="flex mt-16">
          <Categories />
          <div className="flex-1 p-6 ml-64">{children}</div>
        </div>
      </body>
    </html>
  );
}
